---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: {{ .Values.migrateEnvVars.cicdNamespace }}
spec:
  ports:
  - name: "3777"
    port: 3777
    targetPort: 3777
  selector:
    app: client
status:
  loadBalancer: {}
