---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql
  name: graphql
  namespace: {{ .Values.migrateEnvVars.cicdNamespace }}
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: graphql
status:
  loadBalancer: {}
