---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage
  name: storage
  namespace: {{ .Values.migrateEnvVars.cicdNamespace }}
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app: storage
status:
  loadBalancer: {}
