---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: widget
  name: widget
  namespace: {{ .Values.migrateEnvVars.cicdNamespace }}
spec:
  ports:
  - name: "7777"
    port: 7777
    targetPort: 7777
  selector:
    app: widget
status:
  loadBalancer: {}
