---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: api-parkhands-de-redirect
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
          return 301 https://api.parkhands.com$request_uri;
spec:
  tls:
  - hosts:
    - api.parkhands.de
    secretName: parkhands-de-api-tls
  rules:
    - host: api.parkhands.de
      http:
        paths:
          - backend:
              serviceName: graphql
              servicePort: 5000
            path: /
