---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: monitor-parkhands-de-redirect
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
          return 301 https://monitor.parkhands.com$request_uri;
spec:
  tls:
  - hosts:
    - monitor.parkhands.de
    secretName: parkhands-de-monitor-tls
  rules:
    - host: monitor.parkhands.de
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000
            path: /
