{
 "title": "PostgreSQL Performance Analysis - Good",
 "description": "PostgreSQL Performance Analysis",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{namespace=\"$namespace\"})"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{instance=\"$instance\"})"
   }
  ]
 },
 "panels": [
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\"})\n",
     "legendFormat": "Current connections"
    },
    {
     "expr": "sum(pg_settings_max_connections{instance=\"$instance\"})",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{instance=~\"$instance\"}[$__interval])) /\nsum(pg_settings_max_connections{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{namespace=~\"$namespace\",instance=~\"$instance\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{namespace=~\"$namespace\",instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers_per_gather{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "pg_stat_replication_pg_current_wal_lsn_bytes",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_current_wal_lsn_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connection / Transaction Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Connections in detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"$instance\"}",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} SELECT (index scan)"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} INSERT"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} UPDATE"
    },
    {
     "expr": "irate(pg_stat_database_tup_deleted{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} DELETE"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{instance=\"$instance\"}",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\"} / (pg_stat_database_blks_read{instance=\"$instance\"} + pg_stat_database_blks_hit{instance=\"$instance\"})",
     "legendFormat": "{{datname}} Cache Hit Rate"
    }
   ]
  },
  { "title": "misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{instance=\"$instance\"}",
     "legendFormat": "{{datname}} {{mode}}"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} Temp Bytes"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}