---
apiVersion: v1
kind: Secret
metadata:
  name: pgpool-initdb-scripts
  namespace: {{ .Values.migrateEnvVars.cicdNamespace }}
type: Opaque
stringData:
    pgpool_authenticator.sh: |-
      #!/bin/bash

      USERS=("{{ .Values.environmentVariables.DB_USER }}:{{ .Values.secrets.dbPass }}")

      for user in "${USERS[@]}"; do
          user_info=(${user//:/ })
          pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "${user_info[0]}" "${user_info[1]}"
      done
    pgpool_config.sh: |
        #!/bin/bash

        CUSTOM_CONFIG=$(cat <<EOF
        #------------------------------------------------------------------------------
        # CUSTOM SETTINGS (they override the values set above in the config)
        #------------------------------------------------------------------------------

        #log_statement = on
        #log_connections = on
        #disable_load_balance_on_write = always

        EOF
        )

        set -e
