#TODO verify against production version!
---
kind: ConfigMap
metadata:
  name: postgresql-extended-conf
  namespace: {{ .Values.migrateEnvVars.cicdNamespace }}
apiVersion: v1
data:
  extended.conf: |
    #------------------------------------------------------------------------------
    # CUSTOM SETTINGS (they override the values set above in the config)
    #------------------------------------------------------------------------------

    # Configure preloaded libraries
    shared_preload_libraries = 'repmgr,pg_cron,timescaledb,pg_stat_statements'
    cron.database_name = 'app'

    pg_stat_statements.max = 10000
    pg_stat_statements.track = all

    wal_level = 'replica'
    wal_compression = on
    max_wal_senders = 10
    max_replication_slots = 10

    # Disable timescaledb telemetry
    timescaledb.telemetry_level=off

    # PG Tune
    max_connections = 144
    shared_buffers = 1GB
    effective_cache_size = 3GB
    maintenance_work_mem = 256MB
    checkpoint_completion_target = 0.7
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 10485kB
    min_wal_size = 1GB
    max_wal_size = 4GB
    max_worker_processes = 2
    max_parallel_workers_per_gather = 1
    max_parallel_workers = 2
    max_parallel_maintenance_workers = 1

    #------------------------------------------------------------------------------
    # DEV SETTINGS (they override the values set above in the config)
    #------------------------------------------------------------------------------

    # log all queries
    log_statement = 'none'

    logging_collector = 'on'
    log_min_error_statement = 'error'
    log_min_duration_statement = 2000
