---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin
  namespace: {{ CICD_NAMESPACE }}
spec:
  ports:
  - name: "1337"
    port: 1337
    targetPort: 1337
  selector:
    app: admin
status:
  loadBalancer: {}
