---
# Delete jobs that are 3 or more days old
# https://stackoverflow.com/questions/48934491/kubernetes-how-to-delete-pods-based-on-age-creation-time
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-cleanup
  namespace: {{ CICD_NAMESPACE }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 600
      template:
        spec:
          serviceAccountName: job-cleanup
          containers:
          - name: kubectl-runner
            image: dtzar/helm-kubectl:3.1.2
            securityContext:
              allowPrivilegeEscalation: false
            command: ["sh", "-c"]
            args:
              - kubectl delete job --namespace={{ CICD_NAMESPACE }} $(kubectl get job --namespace={{ CICD_NAMESPACE }} | awk 'match($4,/^([3-9]|[1-9][0-9]+)d$/) {print $1}')
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-cleanup
  namespace: {{ CICD_NAMESPACE }}
rules:
  - apiGroups: [batch]
    resources:
      - jobs
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-cleanup
  namespace: {{ CICD_NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: job-cleanup
    namespace: {{ CICD_NAMESPACE }}
roleRef:
  kind: Role
  name: job-cleanup
  apiGroup: rbac.authorization.k8s.io
