---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-autoscaler
  namespace: {{ CICD_NAMESPACE }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: graphql
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: 300m
        type: AverageValue
    type: Resource
  # - resource:
  #     name: memory
  #     target:
  #       averageUtilization: 80
  #       type: Utilization
  #   type: Resource
