apiVersion: v1
kind: Service
metadata:
  labels:
    app: dind
  name: dind
  namespace: dind
spec:
  ports:
  - name: "2375"
    port: 2375
    protocol: TCP
    targetPort: 2375
  selector:
    app: dind
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
