---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backup
  name: backup
  namespace: backup
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app: backup
status:
  loadBalancer: {}
