---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: monitor
  namespace: {{ CICD_NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: nginx-external
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: dico-clusterissuer
    kubernetes.io/ingress.allow-http: "false"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/acme-challenge-type: http01
    #nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - monitor.{{ CICD_GIT_BRANCH }}.{{ ROOT_DOMAIN }}
    secretName: parkhands-monitor-{{ CICD_GIT_BRANCH }}-tls
  rules:
    - host: monitor.{{ CICD_GIT_BRANCH }}.{{ ROOT_DOMAIN }}
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000
            path: /
