---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: storage
  namespace: {{ CICD_NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: nginx-external
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: dico-clusterissuer
    kubernetes.io/ingress.allow-http: "false"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/app-root: /minio
    #nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/configuration-snippet : |
          if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
            expires 365d;
            add_header Cache-Control "public";
          }
spec:
  tls:
  - hosts:
    - storage.{{ CICD_GIT_BRANCH }}.{{ ROOT_DOMAIN }}
    secretName: parkhands-storage-{{ CICD_GIT_BRANCH }}-tls
  rules:
    - host: storage.{{ CICD_GIT_BRANCH }}.{{ ROOT_DOMAIN }}
      http:
        paths:
          - backend:
              serviceName: storage
              servicePort: 9000
            path: /
