---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: widget
  name: widget
  namespace: {{ CICD_NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: widget
  template:
    metadata:
      labels:
        app: widget
    spec:
      imagePullSecrets:
      - name: parkhands-registry-secret
      initContainers:
      - name: wait-graphql
        image: radial/busyboxplus:curl
        securityContext:
          allowPrivilegeEscalation: false
        command: ['sh', '-c']
        args:
          - |
            until curl -sSf -X POST -H "Content-Type: application/json" --data '{"query": "{ languagesList { name } }"}' ${GRAPHQL_API_URL} > /dev/null; do echo waiting for GraphQL API; sleep 2; done;
        env:
        - name: GRAPHQL_API_URL
          value: http://graphql:5000/graphql
      containers:
      - name: ph-widget
        image: {{ REGISTRY_BASE_URL }}/ph_widget:{{ DEPLOY_WIDGET_IMAGE_TAG }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 7777
        env:
        - name: GRAPHQL_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GRAPHQL_API_ENDPOINT
        - name: GRAPHQL_API_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GRAPHQL_API_URL
        - name: GRAPHQL_WS_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: GRAPHQL_WS_URL
        - name: WIDGET_PORT
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: WIDGET_PORT
        - name: WIDGET_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: WIDGET_URL
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: CLIENT_URL
        - name: CDN_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: CDN_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: NODE_ENV
        - name: BUILD_ID
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: BUILD_ID
        - name: NPM_RUN_TARGET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: NPM_RUN_TARGET
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: GOOGLE_MAPS_API_KEY
        livenessProbe:
          tcpSocket:
            port: 7777
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        resources: {}
          # requests:
          #   cpu: 100m
          #   memory: 100Mi
          # limits:
          #   cpu: 200m
          #   memory: 200Mi
        workingDir: /web/widget
      restartPolicy: Always
status: {}
